export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_ROUTE = '/'
export const TEST_ROUTE = '/test'
export const PROFILE_ROUTE = '/pofile'